language: node_js

node_js:
  - 14

cache:
  directories:
    - node_modules

env:
  - SKIP_PREFLIGHT_CHECK=true

install:
  - npm ci
  
script:
  - npm test
  - npm run lint
  - npx commitlint-travis
  - docker build -t ts-template:latest -f Dockerfile.production .
